# Generated by Django 4.1.3 on 2023-02-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendingtrackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
