# Generated by Django 4.1.5 on 2023-02-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spendingtrackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spendingtrackers.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
