# Generated by Django 4.1.3 on 2023-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendingtrackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
