# Generated by Django 3.2.2 on 2023-02-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendingtrackers', '0002_auto_20230211_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
