# Generated by Django 4.1.3 on 2023-02-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spendingtrackers', '0002_rename_category_choices_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spendingtrackers.category')),
            ],
        ),
    ]
