# Generated by Django 4.1.3 on 2023-02-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spendingtrackers', '0002_alter_category_budget_alter_category_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='catetegory_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spendingtrackers.category'),
            preserve_default=False,
        ),
    ]
