# Generated by Django 4.1.3 on 2023-02-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendingtrackers', '0003_transaction_catetegory_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='catetegory_fk',
            new_name='category_fk',
        ),
    ]
